"""HTTP API (FastAPI). Install with the ``api`` extra.

Security notes:
* the API is stateless and uses no cookies, so there is no ambient credential for a
  cross-site request to ride on (CSRF); bodies must be ``application/json``;
* if ``API_TOKEN`` is set, every request needs ``Authorization: Bearer <token>``
  (compared in constant time);
* CORS is off unless ``CORS_ORIGINS`` lists explicit origins;
* session IDs are generated by the server; client-supplied IDs must be 32 hex chars.
"""
# no ``from __future__ import annotations`` here: FastAPI must see the real model classes
import hmac
import os


def create_app(service=None):
    from fastapi import Depends, FastAPI, Header, HTTPException, Request
    from pydantic import BaseModel, Field

    from .service import build_service

    svc = service or build_service()
    token = os.environ.get("API_TOKEN", "")
    app = FastAPI(title="PolicyPilot", version="0.1.0")

    origins = [o.strip() for o in os.environ.get("CORS_ORIGINS", "").split(",") if o.strip()]
    if origins:
        from fastapi.middleware.cors import CORSMiddleware

        app.add_middleware(CORSMiddleware, allow_origins=origins, allow_methods=["POST", "GET"],
                           allow_headers=["Authorization", "Content-Type"], allow_credentials=False)

    def check_auth(authorization: str = Header(default="")) -> None:
        if not token:
            return
        supplied = authorization.removeprefix("Bearer ").strip()
        if not hmac.compare_digest(supplied.encode(), token.encode()):
            raise HTTPException(status_code=401, detail="invalid or missing token")

    class AskRequest(BaseModel):
        question: str = Field(min_length=1, max_length=svc.max_question_chars)
        session_id: str | None = Field(default=None, max_length=64)

    @app.get("/health")
    def health() -> dict:
        return {"status": "ok"}

    @app.post("/ask", dependencies=[Depends(check_auth)])
    async def ask(request: Request, body: AskRequest) -> dict:
        if not request.headers.get("content-type", "").startswith("application/json"):
            raise HTTPException(status_code=415, detail="application/json required")
        return svc.ask(body.question, body.session_id).to_dict()

    return app
